### PR TITLE
post login welcome page [71]

### PR DESCRIPTION
**Pull request by aqeelparpia**
I have included a post login Welcome page with greatings after they have logged back into the web. Since the login is also email based  "This is a personal opinion as i dont think a user wouldnt be happy receiving emails everytime they login unless its an activity confirmation email". Please Review. Thanks

### CODE REVIEW

**Comment by stripedpajamas** [comment]
Hi @aqeelparpia 👋 

Thanks so much for taking the initiative on this PR!! 

So currently our API and Website are coded to interact in a specific way, so new code added (like the UI component you've written here) need to work within the restraints of that interaction. We've decided (for now) to authenticate users without passwords. As a registered user, they "login" by putting in their email address and then clicking the login link sent to them. This is a pattern we've enjoyed elsewhere online. This could definitely change later on in the project, but for now that's how the website and API are coded to interact. 

That being said, the "post-login" and "post-registration" pages need to reflect that interaction. Can you update the PR with these changes?

- Change text to "A login link has been emailed to you. Please click the link to login. You may safely close this page." (The content team might come through and update this wording later, but this is a safe start)
- Change the component name to PostLogin

Even better would be to adjust the current `post-registration` component and make it work for both Registration and Login, making the text dynamic (e.g. "Please click the link to complete registration" and "Please click the link to login"). 

Let me know if you have any questions! Thanks again for helping out!

**Comment by joelwass** [comment]
@stripedpajamas is exactly right. The post-registration or post-login pages should reflect that the current tab is now "dead" i.e. can be closed assuming the user received an auth email.

**Comment by aqeelparpia** [comment]
Hello @stripedpajamas  I totally understand how it works now. At first i wasnt aware about the chain being used in this sytem. I shall totally update the PR with those changes right away. Thank you.

**Comment by joelwass** [comment]
Hi @aqeelparpia!

Thanks so much for taking this task on! Unfortunately new designs came down the pipeline and this is no longer applicable. I'm really sorry, feel free to grab another issue and we really appreciate the initiative!

**Pull request closed without merging**
