### PR TITLE
Issue 10

### PR DESCRIPTION
**Pull request by jatinkumarg**

### CODE REVIEW

**Comment by jatinkumarg** [comment]
Sorry, I accidentally submitted this PR

**Comment by joelwass** [comment]
@jatinkumarg i wasn't sure if it was ready. looked fine so i merged it

**Comment by jatinkumarg** [comment]
@joelwass The PR submitted before is fine. 

Since I am new to Git, I was trying to sync changes to my forked repo and accident submitted this PR

**Comment by joelwass** [comment]
@jatinkumarg i don't think you can "delete" a PR. it's closed, so i wouldn't worry about it

**Pull request closed without merging**
