### PR TITLE
Heading color contrast update to meet accessibility standards.

### PR DESCRIPTION
**Pull request by thomasean**
Small PR - The title and sub title in the hero image does have sufficient color contrast that meets WCAG 2 AA contrast ration thresholds. Changed the color to be white for better contrast.

### CODE REVIEW

**Comment by joelwass** [comment]
This is awesome but goes against our design. How can we solve this site wide without changing just the header and sub text color?

**Comment by joelwass** [comment]
Let me loop in our designer

**Comment by thomasean** [comment]
I recommend using Chromes built in Accessibility audit tool or a plugin called Axe (available for all major browsers).  Run a quick scan and checkout the results! I'm happy to assist with site wide changes once you have a direction you'd like to go.

**Comment by joelwass** [comment]
Our designer gave the thumbs up! Thanks for bringing this to our attention @thomasean !

**Pull request merged**
