### PR TITLE
Make font sizes consistent and in line with design

### PR DESCRIPTION
**Pull request by arturoalviar**
This addresses issue #150.

## Overview
- I went through and matched the font sizes as close as possible to the design comps. 
- I introduced a new font size class but tried to use Taychons font size classes as much as possible.
- I also modified the Taychons classes in some sections to accommodate new text styles and to match the design comp.

### CODE REVIEW

**Comment by meowwwls** [comment]
On my computer (13" Retina display laptop), the text is overflowing from the amount raised:
numbers overflowing from 'amount raised' section of The Teacher Fund website

The copy on the index page is huge, but it is still really small and hard to read on the Mission page.

**Comment by arturoalviar** [comment]
@meowwwls I did not style the cards in the See How We're Doing section since I wanted to focus primary on adjusting fonts. Currently, they have a fixed height and width so that explains the overflow.

The font is indeed large but it is how it is presented in the design comps.

The [link to the designs](https://xd.adobe.com/spec/39899b04-1c47-452f-7902-d76fed55d62e-4fb8/grid) did not provide a mockup for the Mission page so that is why that page was left untouched.

**Comment by joelwass** [comment]
I'd try to stay consistent across the webapp even thought it might not exist in the designs.

Also i think @meowwwls 's comment regarding the overflowing amount in desktop index page still exists. Those texts seem quite large, no?

**Comment by arturoalviar** [comment]
Yeah the font size is quite large, 70px as described in the design mock. I can change the breakpoint for this class (currently applies to screens above 1024px) or I can lower the font size to Tachyons's f1 class which is ~48px.

I did not address the overflowing text but I can in my next commit.

As for the Mission page, I can bump up the text size to match the body copy of the index page.

**Comment by joelwass** [comment]
There are conflicts in this PR still.

Additionally, if you click the "View deployment" that zeit spins up for us, you can see that the splash page no longer looks very crisp. this might be a flaw of actual screen size vs the screen size of the designs, but this PR can't be merged when the page looks like it does

**Pull request closed without merging**
