### PR TITLE
Adding smaller images

### PR DESCRIPTION
**Pull request by EricNewcombe**
Pull request to fix issue #99 

Changed file size to make small medium and large version of each image used in the code. Image widths I decided on based on what seemed appropriate with the site layout on the page it was displayed.

### CODE REVIEW

**Comment by joelwass** [comment]
Thank you!

We are reviewing these changes to determine if it's the best path for the code base to go down. We'll keep you updated!

**Comment by joelwass** [comment]
I don't think this PR is in the right direction @EricNewcombe :/ sorry about that. We'd prefer to keep picture adjustments within media queries in scss files. Uploading the different picture sizes is a great start though! 

Could you coordinate with @meowwwls on how to decrease the image size footprint for all of your different image sizes and then remove the javascript screensize computation?

**Comment by joelwass** [comment]
Also changing the jpg to png's would probably be best since that's the web standard

**Comment by meowwwls** [comment]
Hey @EricNewcombe. Instead of relying on JavaScript to show different size images at different screen sizes, I think a better method would be to utilize the `<picture>` element to create image breakpoints for inline images, and use CSS media queries if you want to change background images.

- [Information on how to use the `<picture>` element and responsive background images](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)

- [More information on the `<picture>` element](https://alligator.io/html/picture-element/)

**Pull request closed without merging**
